data:
  dataset: CIFAR100 # choices: [MNIST, CIFAR10, CIFAR100, TINY-IMAGENET, IMAGENET]
  in_channels: 3
  num_classes: 100
  dataset_dir: /home/hbouzidi/hbouzidi/datasets/cifar-100
  batch_size: 128
  data_loader_workers_per_gpu: 4
  distributed: False
  augment: auto_augment_tf

train:
  model_name: simple_cnn # choices: [simple_cnn, depth_cnn, bottle_cnn, dynamic_cnn, resnet_cnn, asymetric_cnn]
  width_multi: 1.0
  depth_multi: 5
  epochs: 300
  optimizer: sgd
  learning_rate: 0.01 
  weight_decay: 0.001 

run: 
  seed: 1234 
  saved_models: ./saved_models